/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafebilling;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author shrut
 */
public class billing extends javax.swing.JFrame {

    /**
     * Creates new form billing
     */
    public billing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date = new javax.swing.JTextField();
        orderId = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        bchk1 = new javax.swing.JCheckBox();
        bchk2 = new javax.swing.JCheckBox();
        bchk3 = new javax.swing.JCheckBox();
        bchk4 = new javax.swing.JCheckBox();
        bchk5 = new javax.swing.JCheckBox();
        bs1 = new javax.swing.JTextField();
        bs2 = new javax.swing.JTextField();
        bs3 = new javax.swing.JTextField();
        bs4 = new javax.swing.JTextField();
        bs5 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        b5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        schk1 = new javax.swing.JCheckBox();
        ss1 = new javax.swing.JTextField();
        s1 = new javax.swing.JTextField();
        schk2 = new javax.swing.JCheckBox();
        ss2 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        schk3 = new javax.swing.JCheckBox();
        ss3 = new javax.swing.JTextField();
        s3 = new javax.swing.JTextField();
        schk4 = new javax.swing.JCheckBox();
        ss4 = new javax.swing.JTextField();
        s4 = new javax.swing.JTextField();
        schk5 = new javax.swing.JCheckBox();
        ss5 = new javax.swing.JTextField();
        s5 = new javax.swing.JTextField();
        m5 = new javax.swing.JTextField();
        ms5 = new javax.swing.JTextField();
        mchk5 = new javax.swing.JCheckBox();
        m4 = new javax.swing.JTextField();
        ms4 = new javax.swing.JTextField();
        mchk4 = new javax.swing.JCheckBox();
        m3 = new javax.swing.JTextField();
        ms3 = new javax.swing.JTextField();
        mchk3 = new javax.swing.JCheckBox();
        m2 = new javax.swing.JTextField();
        ms2 = new javax.swing.JTextField();
        mchk2 = new javax.swing.JCheckBox();
        m1 = new javax.swing.JTextField();
        ms1 = new javax.swing.JTextField();
        mchk1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dchk1 = new javax.swing.JCheckBox();
        ds1 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        dchk2 = new javax.swing.JCheckBox();
        ds2 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        dchk3 = new javax.swing.JCheckBox();
        ds3 = new javax.swing.JTextField();
        d3 = new javax.swing.JTextField();
        dchk4 = new javax.swing.JCheckBox();
        ds4 = new javax.swing.JTextField();
        d4 = new javax.swing.JTextField();
        dchk5 = new javax.swing.JCheckBox();
        ds5 = new javax.swing.JTextField();
        d5 = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        Total = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        pay = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 180, 30));

        orderId.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        orderId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(orderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 194, 60, -1));

        Name.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 270, -1));

        bchk1.setBackground(new java.awt.Color(102, 51, 0));
        bchk1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bchk1.setForeground(new java.awt.Color(255, 255, 255));
        bchk1.setText("Cappuccino    120/-");
        getContentPane().add(bchk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        bchk2.setBackground(new java.awt.Color(102, 51, 0));
        bchk2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bchk2.setForeground(new java.awt.Color(255, 255, 255));
        bchk2.setText("Mocha              200/-");
        bchk2.setActionCommand("Mocha               200/-");
        getContentPane().add(bchk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        bchk3.setBackground(new java.awt.Color(102, 51, 0));
        bchk3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bchk3.setForeground(new java.awt.Color(255, 255, 255));
        bchk3.setText("Cold Coffee    100/-");
        bchk3.setActionCommand("Cold Coffee   200/-");
        getContentPane().add(bchk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 180, -1));

        bchk4.setBackground(new java.awt.Color(102, 51, 0));
        bchk4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bchk4.setForeground(new java.awt.Color(255, 255, 255));
        bchk4.setText("Hot Chocolate 120/-");
        bchk4.setActionCommand("Cold Coffee   200/-");
        getContentPane().add(bchk4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        bchk5.setBackground(new java.awt.Color(102, 51, 0));
        bchk5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bchk5.setForeground(new java.awt.Color(255, 255, 255));
        bchk5.setText("Milkshake      120/-");
        bchk5.setActionCommand("Cold Coffee   200/-");
        getContentPane().add(bchk5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));
        getContentPane().add(bs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 20, -1));
        getContentPane().add(bs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 20, -1));
        getContentPane().add(bs3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 20, -1));
        getContentPane().add(bs4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 20, -1));
        getContentPane().add(bs5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 20, -1));

        b1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 40, -1));

        b2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 40, -1));

        b3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 40, -1));

        b4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 40, -1));

        b5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 40, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Amt.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QTY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QTY");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amt.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        schk1.setBackground(new java.awt.Color(102, 51, 0));
        schk1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        schk1.setForeground(new java.awt.Color(255, 255, 255));
        schk1.setText("Veg Burger    100/-");
        getContentPane().add(schk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));
        getContentPane().add(ss1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 20, -1));

        s1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        getContentPane().add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 40, -1));

        schk2.setBackground(new java.awt.Color(102, 51, 0));
        schk2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        schk2.setForeground(new java.awt.Color(255, 255, 255));
        schk2.setText("Crispy Wrap  120/-");
        schk2.setActionCommand("Mocha               200/-");
        getContentPane().add(schk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));
        getContentPane().add(ss2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 20, -1));

        s2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 40, -1));

        schk3.setBackground(new java.awt.Color(102, 51, 0));
        schk3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        schk3.setForeground(new java.awt.Color(255, 255, 255));
        schk3.setText("Garlic Bread 150/-");
        schk3.setActionCommand("Cold Coffee   200/-");
        schk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schk3ActionPerformed(evt);
            }
        });
        getContentPane().add(schk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 180, -1));
        getContentPane().add(ss3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 20, -1));

        s3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 40, -1));

        schk4.setBackground(new java.awt.Color(102, 51, 0));
        schk4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        schk4.setForeground(new java.awt.Color(255, 255, 255));
        schk4.setText("Cheese Balls  140/-");
        schk4.setActionCommand("Cold Coffee   200/-");
        getContentPane().add(schk4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));
        getContentPane().add(ss4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 20, -1));

        s4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 40, -1));

        schk5.setBackground(new java.awt.Color(102, 51, 0));
        schk5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        schk5.setForeground(new java.awt.Color(255, 255, 255));
        schk5.setText("Cutlets            120/-");
        schk5.setActionCommand("Cold Coffee   200/-");
        getContentPane().add(schk5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));
        getContentPane().add(ss5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 20, -1));

        s5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 40, -1));

        m5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(m5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 40, -1));
        getContentPane().add(ms5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 20, -1));

        mchk5.setBackground(new java.awt.Color(102, 51, 0));
        mchk5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mchk5.setForeground(new java.awt.Color(255, 255, 255));
        mchk5.setText("Apple Cinnamon 150/-");
        mchk5.setActionCommand("Cold Coffee   200/-");
        getContentPane().add(mchk5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        m4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 40, -1));
        getContentPane().add(ms4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 20, -1));

        mchk4.setBackground(new java.awt.Color(102, 51, 0));
        mchk4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mchk4.setForeground(new java.awt.Color(255, 255, 255));
        mchk4.setText("Banana                140/-");
        mchk4.setActionCommand("Cold Coffee   200/-");
        getContentPane().add(mchk4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, -1));

        m3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 40, -1));
        getContentPane().add(ms3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 20, -1));

        mchk3.setBackground(new java.awt.Color(102, 51, 0));
        mchk3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        mchk3.setForeground(new java.awt.Color(255, 255, 255));
        mchk3.setText("Coffee Cake     120/-");
        mchk3.setActionCommand("Cold Coffee   200/-");
        getContentPane().add(mchk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 190, -1));

        m2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 40, -1));
        getContentPane().add(ms2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 20, -1));

        mchk2.setBackground(new java.awt.Color(102, 51, 0));
        mchk2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        mchk2.setForeground(new java.awt.Color(255, 255, 255));
        mchk2.setText("Chocolate Chip 120/-");
        mchk2.setActionCommand("Mocha               200/-");
        getContentPane().add(mchk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        m1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 40, -1));
        getContentPane().add(ms1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 20, -1));

        mchk1.setBackground(new java.awt.Color(102, 51, 0));
        mchk1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        mchk1.setForeground(new java.awt.Color(255, 255, 255));
        mchk1.setText("Blueberry        150/-  ");
        getContentPane().add(mchk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Amt.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("QTY");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("QTY");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 270, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Amt.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 270, -1, -1));

        dchk1.setBackground(new java.awt.Color(102, 51, 0));
        dchk1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dchk1.setForeground(new java.awt.Color(255, 255, 255));
        dchk1.setText("Apple Pie        150/-  ");
        getContentPane().add(dchk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 180, -1));
        getContentPane().add(ds1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 290, 20, -1));

        d1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, 40, -1));

        dchk2.setBackground(new java.awt.Color(102, 51, 0));
        dchk2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dchk2.setForeground(new java.awt.Color(255, 255, 255));
        dchk2.setText("Cheese Cake    120/-");
        dchk2.setActionCommand("Mocha               200/-");
        getContentPane().add(dchk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 180, -1));
        getContentPane().add(ds2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 330, 20, -1));

        d2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, 40, -1));

        dchk3.setBackground(new java.awt.Color(102, 51, 0));
        dchk3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dchk3.setForeground(new java.awt.Color(255, 255, 255));
        dchk3.setText("Glazed Doughnut 175/-");
        dchk3.setActionCommand("Cold Coffee   200/-");
        getContentPane().add(dchk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 180, -1));
        getContentPane().add(ds3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 370, 20, -1));

        d3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 370, 40, -1));

        dchk4.setBackground(new java.awt.Color(102, 51, 0));
        dchk4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dchk4.setForeground(new java.awt.Color(255, 255, 255));
        dchk4.setText("Red Velvet Fudge 200/-");
        dchk4.setActionCommand("Cold Coffee   200/-");
        getContentPane().add(dchk4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 180, -1));
        getContentPane().add(ds4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 410, 20, -1));

        d4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 410, 40, -1));

        dchk5.setBackground(new java.awt.Color(102, 51, 0));
        dchk5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dchk5.setForeground(new java.awt.Color(255, 255, 255));
        dchk5.setText("Sizzling Brownie 200/-");
        dchk5.setActionCommand("Cold Coffee   200/-");
        getContentPane().add(dchk5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 180, -1));
        getContentPane().add(ds5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 450, 20, -1));

        d5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(d5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, 40, -1));

        amount.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 70, 40));

        Total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Total.setText("TOTAL AMOUNT");
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 180, 40));

        BACK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, -1, -1));

        pay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pay.setText("PAY");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        getContentPane().add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafebilling/billing.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m1ActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d1ActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
        int AMOUNT,q,price;
        if(bchk1.isSelected( )==true){
            q = Integer.parseInt(bs1.getText( ));
            b1.setText(""+(150*q));
        }
        else {
            b1.setText(""+0);
            bs1.setText(""+0);
        }
        
        if(bchk2.isSelected( )==true){
            q = Integer.parseInt(bs2.getText( ));
            b2.setText(""+(200*q));
        }
        else{
            b2.setText(""+0);
            bs2.setText(""+0);
        }
        
        if(bchk3.isSelected( )==true){
            q = Integer.parseInt(bs3.getText( ));
             b3.setText(""+(100*q));
        }
        else{
            b3.setText(""+0);
            bs3.setText(""+0);
        }
        
        if(bchk4.isSelected( )==true){
            q = Integer.parseInt(bs4.getText( ));
            b4.setText(""+(120*q));
        }
        else {
            b4.setText(""+0);
            bs4.setText(""+0);
        }
        
        if(bchk5.isSelected( )==true){
            q = Integer.parseInt(bs5.getText( ));
            b5.setText(""+(120*q));
        }
        else {
            b5.setText(""+0);
            bs5.setText(""+0);
        }
 
        if(schk1.isSelected( )==true){
            q = Integer.parseInt(ss1.getText( ));
            s1.setText(""+(100*q));
        }
        else
        { 
            s1.setText(""+0);
            ss1.setText(""+0);
        }


        if(schk2.isSelected( )==true){
             q = Integer.parseInt(ss2.getText( ));
            s2.setText(""+(120*q));
        }

        else{
            s2.setText(""+0);
            ss2.setText(""+0);
        }
        
        if(schk3.isSelected( )==true){
            q = Integer.parseInt(ss3.getText( ));
            s3.setText(""+(150*q));
        }
        else
        { 
            s3.setText(""+0);
            ss3.setText(""+0);
        }
 
        if(schk4.isSelected( )==true){
            q = Integer.parseInt(ss4.getText( ));
            s4.setText(""+(140*q));
        }
        else
        { 
            s4.setText(""+0);
            ss4.setText(""+0);
        }
 
        if(schk5.isSelected( )==true){
            q = Integer.parseInt(ss5.getText( ));
            s5.setText(""+(120*q));
        }
        else
        { 
            s5.setText(""+0);
            ss5.setText(""+0);
        }

        if(mchk1.isSelected( )==true){
            q = Integer.parseInt(ms1.getText( ));
            m1.setText(""+(150*q));
        }
        else
        { 
            m1.setText(""+0);
            ms1.setText(""+0);
        }
 
        if(mchk2.isSelected( )==true){
            q = Integer.parseInt(ms2.getText( ));
            m2.setText(""+(120*q));
        }
        else
        { 
            m2.setText(""+0);
            ms2.setText(""+0);
        }
        
        if(mchk3.isSelected( )==true){
            q = Integer.parseInt(ms3.getText( ));
            m3.setText(""+(120*q));
        }
        else
        {
            m3.setText(""+0);
            ms3.setText(""+0);
        }
    
        if(mchk4.isSelected( )==true){
            q = Integer.parseInt(ms4.getText( ));
            m4.setText(""+(140*q));
        }
        else
        { 
            m4.setText(""+0);
            ms4.setText(""+0); 
        }
        
        if(mchk5.isSelected( )==true){
            q = Integer.parseInt(ms5.getText( ));
            m5.setText(""+(150*q));
        }
        else
        { 
            m5.setText(""+0);
            ms5.setText(""+0);
        }
        
        if(dchk1.isSelected( )==true){
            q = Integer.parseInt(ds1.getText( ));
            d1.setText(""+(150*q));
        }
        else
        { 
            d1.setText(""+0);
            ds1.setText(""+0);
        }
        
        if(dchk2.isSelected( )==true){
            q = Integer.parseInt(ds2.getText( ));
            d2.setText(""+(120*q));
        }
        else
        { 
            d2.setText(""+0);
            ds2.setText(""+0);
        }
        
        if(dchk3.isSelected( )==true){
            q = Integer.parseInt(ds3.getText( ));
            d3.setText(""+(175*q));
        }
        else{
            d3.setText(""+0);
            ds3.setText(""+0);
        }
 
        if(dchk4.isSelected( )==true){
            q = Integer.parseInt(ds4.getText( ));
            d4.setText(""+(200*q));
        }
        else
        { 
            d4.setText(""+0);
            ds4.setText(""+0);
        }
 
        if(dchk5.isSelected( )==true){
            q = Integer.parseInt(ds5.getText( ));
            d5.setText(""+(200*q));
        }
       else
        { 
            d5.setText(""+0);
            ds5.setText(""+0);
        }

        AMOUNT=((Integer.parseInt(b1.getText())+Integer.parseInt(b2.getText())+
        Integer.parseInt(b3.getText())+Integer.parseInt(b4.getText())+Integer.parseInt(b5.getText())+
        Integer.parseInt(s1.getText())+Integer.parseInt(s2.getText())+Integer.parseInt(s3.getText())+
        Integer.parseInt(s4.getText())+Integer.parseInt(s5.getText())+Integer.parseInt(m1.getText())+
        Integer.parseInt(m2.getText())+Integer.parseInt(m3.getText())+Integer.parseInt(m4.getText())+
        Integer.parseInt(m5.getText())+Integer.parseInt(d1.getText())+Integer.parseInt(d2.getText())+
        Integer.parseInt(d3.getText())+Integer.parseInt(d4.getText())+Integer.parseInt(d5.getText())));
 
        amount.setText(""+AMOUNT); 
        
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Cafe"+"?useSSL=false","root","12345");
            Statement stmt = (Statement) con.createStatement( );
            
            String query="SELECT (max(OrderID)+1) FROM report;";
            ResultSet rs=stmt.executeQuery(query);
            
            if (rs.next( ))
            {
                String order_id=rs.getString("(Max(OrderID)+1)");
                orderId.setText(order_id);
            }
            else{
                orderId.setText("1");
            }
            
            
            String query1="SELECT CURRENT_DATE;";
            ResultSet rs1=stmt.executeQuery(query1); 
            
            if (rs1.next( ))
            {
            String DATE=rs1.getString("CURRENT_DATE");
            date.setText(DATE);
            orderId.setEditable(false);
            date.setEditable(false);
            amount.setEditable(false);
} 

            } catch (Exception e) {}
    }//GEN-LAST:event_TotalActionPerformed

    private void schk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schk3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schk3ActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
        if(amount.getText( ).equals("0"))
            JOptionPane.showMessageDialog(this,"Choose your Order");
        else{
            
            int OrderID;
            if(orderId.getText().isEmpty())
                OrderID = 1;
            else 
                OrderID = Integer.parseInt(orderId.getText());
            String name = Name.getText( ),f;
            String Date = date.getText();
            int amt=Integer.parseInt(amount.getText( ));
            
            if(name.isEmpty( )){
                f=JOptionPane.showInputDialog(this,"ENTER CUSTOMER'S NAME");
                if(f!=null)
                    name=f; 
            }
                try{
                   
                Class.forName("java.sql.DriverManager");
                Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Cafe"+"?useSSL=false","root","12345");
                Statement stmt=(Statement)con.createStatement();
                
                String query="INSERT INTO report VALUES('"+OrderID+"','"+name+"','"+Date+"','"+amt+"');";
                stmt.executeUpdate(query);

                }
                catch(Exception e){} 

                JOptionPane.showMessageDialog(this,"Amount Paid Successfully");


                bchk1.setSelected(false); //reset all field after entering values in records
                bchk2.setSelected(false);
                bchk3.setSelected(false);
                bchk4.setSelected(false);
                bchk5.setSelected(false);
                schk1.setSelected(false);
                schk2.setSelected(false);
                schk3.setSelected(false);
                schk4.setSelected(false);
                schk5.setSelected(false);
                mchk1.setSelected(false);
                mchk2.setSelected(false);
                mchk3.setSelected(false);
                mchk4.setSelected(false);
                mchk5.setSelected(false);
                dchk1.setSelected(false);
                dchk2.setSelected(false);
                dchk3.setSelected(false);
                dchk4.setSelected(false);
                dchk5.setSelected(false);
                b1.setText("");
                bs1.setText("");
                b2.setText("");
                bs2.setText("");
                b3.setText("");
                bs3.setText("");
                b4.setText("");
                bs4.setText("");
                b5.setText("");
                bs5.setText("");
                s1.setText("");
                ss1.setText("");
                s2.setText("");
                ss2.setText("");
                s3.setText("");
                ss3.setText("");
                s4.setText("");
                ss4.setText("");
                s5.setText("");
                ss5.setText("");
                m1.setText("");
                ms1.setText("");
                m2.setText("");
                ms2.setText("");
                m3.setText("");
                ms3.setText("");
                m4.setText("");
                ms4.setText("");
                m5.setText("");
                ms5.setText("");
                d1.setText("");
                ds1.setText("");
                d2.setText("");
                ds2.setText("");
                d3.setText("");
                ds3.setText("");
                d4.setText("");
                ds4.setText("");
                d5.setText("");
                ds5.setText("");
                Name.setText("");
                amount.setText("");
                orderId.setText("");
                date.setText("");
            }
            
         

    }//GEN-LAST:event_payActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        // TODO add your handling code here:
        this.dispose( );
        new MAIN_WINDOW( ).setVisible(true);
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JTextField Name;
    private javax.swing.JButton Total;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JTextField b5;
    private javax.swing.JLabel background;
    private javax.swing.JCheckBox bchk1;
    private javax.swing.JCheckBox bchk2;
    private javax.swing.JCheckBox bchk3;
    private javax.swing.JCheckBox bchk4;
    private javax.swing.JCheckBox bchk5;
    private javax.swing.JTextField bs1;
    private javax.swing.JTextField bs2;
    private javax.swing.JTextField bs3;
    private javax.swing.JTextField bs4;
    private javax.swing.JTextField bs5;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField d3;
    private javax.swing.JTextField d4;
    private javax.swing.JTextField d5;
    private javax.swing.JTextField date;
    private javax.swing.JCheckBox dchk1;
    private javax.swing.JCheckBox dchk2;
    private javax.swing.JCheckBox dchk3;
    private javax.swing.JCheckBox dchk4;
    private javax.swing.JCheckBox dchk5;
    private javax.swing.JTextField ds1;
    private javax.swing.JTextField ds2;
    private javax.swing.JTextField ds3;
    private javax.swing.JTextField ds4;
    private javax.swing.JTextField ds5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField m5;
    private javax.swing.JCheckBox mchk1;
    private javax.swing.JCheckBox mchk2;
    private javax.swing.JCheckBox mchk3;
    private javax.swing.JCheckBox mchk4;
    private javax.swing.JCheckBox mchk5;
    private javax.swing.JTextField ms1;
    private javax.swing.JTextField ms2;
    private javax.swing.JTextField ms3;
    private javax.swing.JTextField ms4;
    private javax.swing.JTextField ms5;
    private javax.swing.JTextField orderId;
    private javax.swing.JButton pay;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JTextField s5;
    private javax.swing.JCheckBox schk1;
    private javax.swing.JCheckBox schk2;
    private javax.swing.JCheckBox schk3;
    private javax.swing.JCheckBox schk4;
    private javax.swing.JCheckBox schk5;
    private javax.swing.JTextField ss1;
    private javax.swing.JTextField ss2;
    private javax.swing.JTextField ss3;
    private javax.swing.JTextField ss4;
    private javax.swing.JTextField ss5;
    // End of variables declaration//GEN-END:variables
}
