/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafebilling;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shrut
 */
public class report extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    public report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rb2 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        back = new javax.swing.JButton();
        show = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Summary");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        rb2.setText("All Orders");
        rb2.setBorder(null);
        rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 140, 30));

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        rb1.setText("Current Month Orders");
        rb1.setBorder(null);
        rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 260, 30));

        back.setFont(new java.awt.Font("Tahoma", 3, 19)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 110, 30));

        show.setFont(new java.awt.Font("Tahoma", 3, 19)); // NOI18N
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 110, 30));

        tb1.setBackground(new java.awt.Color(204, 204, 204));
        tb1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "Customer_Name", "Date", "Bill_Amount"
            }
        ));
        tb1.setGridColor(new java.awt.Color(153, 153, 153));
        tb1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                tb1ComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 610, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafebilling/report.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)tb1.getModel( );
        int rows=model.getRowCount( );
 
        if(rows>0){
            for(int i=0;i<rows;i++)
                model.removeRow(0);
        }
        
        try{
            
            Class.forName("java.sql.DriverManager");
            Connection con= (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Cafe"+"?useSSL=false","root","12345");
            Statement stmt=(Statement)con.createStatement( );
            String query = null;
            
            if(rb1.isSelected( ))
                query="SELECT * FROM report WHERE MONTH(Date)=MONTH(CURRENT_DATE) and YEAR(Date)=Year(CURRENT_DATE);";
            
            else if(rb2.isSelected( ))
                query="SELECT * FROM REPORT;";
            
            ResultSet rs= stmt.executeQuery(query);
            while(rs.next( )){
                int OrderID = rs.getInt("OrderID");
                String Cust_Name=rs.getString("Cust_Name");
                String Date=rs.getString("Date"); 
                int Bill_Amt=rs.getInt("Bill_Amt");
 
                model.addRow(new Object[ ] {OrderID,Cust_Name,Date,Bill_Amt});
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"No Records Found!");
        }

    }//GEN-LAST:event_showActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose( );
        new MAIN_WINDOW().setVisible(true); 

    }//GEN-LAST:event_backActionPerformed

    private void tb1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tb1ComponentResized
        // TODO add your handling code here:
        tb1.setRowHeight(24);
    }//GEN-LAST:event_tb1ComponentResized
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JButton show;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
